version: "3"
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=default_cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-server:9092
    depends_on:
      - kafka-server

  kafka-server:
    container_name: kafka-server
    build:
      context: .
    image: kafka-server
    ports:
      - 9092:9092
    volumes:
      - ./server.properties:/mnt/kafka/config/kraft/server.properties 
      - ./logs:/mnt/kafka/logs